# Generated by Django 2.2.5 on 2019-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
