# Generated by Django 2.2.5 on 2019-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_email_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
