# Generated by Django 2.2.4 on 2019-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_email_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
