# Generated by Django 2.2.4 on 2019-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_email_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='PST Pacific Standard Time California UTC 08:00', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
