# Generated by Django 2.2.4 on 2019-09-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190919_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
