# Generated by Django 2.2.4 on 2019-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20190919_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
