# Generated by Django 2.2.4 on 2019-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20190919_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forward_to_email',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
